//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Materia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD FUNCTION.
        /// </summary>
        public static string BUTTON_ADD_FUNCTION {
            get {
                return ResourceManager.GetString("BUTTON_ADD_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD PARAMETER.
        /// </summary>
        public static string BUTTON_ADD_PARAMETER {
            get {
                return ResourceManager.GetString("BUTTON_ADD_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string BUTTON_ALL {
            get {
                return ResourceManager.GetString("BUTTON_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        public static string BUTTON_APPLY {
            get {
                return ResourceManager.GetString("BUTTON_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string BUTTON_CLEAR {
            get {
                return ResourceManager.GetString("BUTTON_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        public static string BUTTON_CREATE {
            get {
                return ResourceManager.GetString("BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT.
        /// </summary>
        public static string BUTTON_EXPORT {
            get {
                return ResourceManager.GetString("BUTTON_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN.
        /// </summary>
        public static string BUTTON_OPEN {
            get {
                return ResourceManager.GetString("BUTTON_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE.
        /// </summary>
        public static string BUTTON_REMOVE {
            get {
                return ResourceManager.GetString("BUTTON_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        public static string BUTTON_RESET {
            get {
                return ResourceManager.GetString("BUTTON_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        public static string BUTTON_SELECT {
            get {
                return ResourceManager.GetString("BUTTON_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string DROPDOWN_BLANK {
            get {
                return ResourceManager.GetString("DROPDOWN_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBR Full.
        /// </summary>
        public static string DROPDOWN_PBR_FULL {
            get {
                return ResourceManager.GetString("DROPDOWN_PBR_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBR - No Height.
        /// </summary>
        public static string DROPDOWN_PBR_NO_HEIGHT {
            get {
                return ResourceManager.GetString("DROPDOWN_PBR_NO_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBR - No Height, AO.
        /// </summary>
        public static string DROPDOWN_PBR_NO_HEIGHT_AO {
            get {
                return ResourceManager.GetString("DROPDOWN_PBR_NO_HEIGHT_AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBR - No Height, AO, Normal.
        /// </summary>
        public static string DROPDOWN_PBR_NO_HEIGHT_AO_NORMAL {
            get {
                return ResourceManager.GetString("DROPDOWN_PBR_NO_HEIGHT_AO_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute Size.
        /// </summary>
        public static string GRAPH_Absolute_Size {
            get {
                return ResourceManager.GetString("GRAPH_Absolute_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string GRAPH_Alignment {
            get {
                return ResourceManager.GetString("GRAPH_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string GRAPH_Alpha {
            get {
                return ResourceManager.GetString("GRAPH_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Channel.
        /// </summary>
        public static string GRAPH_Alpha_Channel {
            get {
                return ResourceManager.GetString("GRAPH_Alpha_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Mode.
        /// </summary>
        public static string GRAPH_Alpha_Mode {
            get {
                return ResourceManager.GetString("GRAPH_Alpha_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient.
        /// </summary>
        public static string GRAPH_Ambient {
            get {
                return ResourceManager.GetString("GRAPH_Ambient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string GRAPH_Angle {
            get {
                return ResourceManager.GetString("GRAPH_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string GRAPH_Basic {
            get {
                return ResourceManager.GetString("GRAPH_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blending.
        /// </summary>
        public static string GRAPH_Blending {
            get {
                return ResourceManager.GetString("GRAPH_Blending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloom Intensity.
        /// </summary>
        public static string GRAPH_Bloom_Intensity {
            get {
                return ResourceManager.GetString("GRAPH_Bloom_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string GRAPH_Blue {
            get {
                return ResourceManager.GetString("GRAPH_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Channel.
        /// </summary>
        public static string GRAPH_Blue_Channel {
            get {
                return ResourceManager.GetString("GRAPH_Blue_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur Intensity.
        /// </summary>
        public static string GRAPH_Blur_Intensity {
            get {
                return ResourceManager.GetString("GRAPH_Blur_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Z.
        /// </summary>
        public static string GRAPH_Camera_Z {
            get {
                return ResourceManager.GetString("GRAPH_Camera_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip Height.
        /// </summary>
        public static string GRAPH_Clip_Height {
            get {
                return ResourceManager.GetString("GRAPH_Clip_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string GRAPH_Color {
            get {
                return ResourceManager.GetString("GRAPH_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string GRAPH_Comment {
            get {
                return ResourceManager.GetString("GRAPH_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string GRAPH_Content {
            get {
                return ResourceManager.GetString("GRAPH_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Output Result.
        /// </summary>
        public static string GRAPH_Current_Output_Result {
            get {
                return ResourceManager.GetString("GRAPH_Current_Output_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Functions.
        /// </summary>
        public static string GRAPH_Custom_Functions {
            get {
                return ResourceManager.GetString("GRAPH_Custom_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Parameters.
        /// </summary>
        public static string GRAPH_Custom_Parameters {
            get {
                return ResourceManager.GetString("GRAPH_Custom_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string GRAPH_Debug {
            get {
                return ResourceManager.GetString("GRAPH_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string GRAPH_Default {
            get {
                return ResourceManager.GetString("GRAPH_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Texture Format.
        /// </summary>
        public static string GRAPH_Default_Texture_Format {
            get {
                return ResourceManager.GetString("GRAPH_Default_Texture_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GRAPH_Description {
            get {
                return ResourceManager.GetString("GRAPH_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string GRAPH_Direction {
            get {
                return ResourceManager.GetString("GRAPH_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string GRAPH_Display {
            get {
                return ResourceManager.GetString("GRAPH_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distortion.
        /// </summary>
        public static string GRAPH_Distortion {
            get {
                return ResourceManager.GetString("GRAPH_Distortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string GRAPH_Effects {
            get {
                return ResourceManager.GetString("GRAPH_Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        public static string GRAPH_Elevation {
            get {
                return ResourceManager.GetString("GRAPH_Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment HDR.
        /// </summary>
        public static string GRAPH_Environment_HDR {
            get {
                return ResourceManager.GetString("GRAPH_Environment_HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far.
        /// </summary>
        public static string GRAPH_Far {
            get {
                return ResourceManager.GetString("GRAPH_Far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string GRAPH_Font {
            get {
                return ResourceManager.GetString("GRAPH_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string GRAPH_Font_Size {
            get {
                return ResourceManager.GetString("GRAPH_Font_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma.
        /// </summary>
        public static string GRAPH_Gamma {
            get {
                return ResourceManager.GetString("GRAPH_Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GRAPH_General {
            get {
                return ResourceManager.GetString("GRAPH_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Lines Display.
        /// </summary>
        public static string GRAPH_Graph_Lines_Display {
            get {
                return ResourceManager.GetString("GRAPH_Graph_Lines_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string GRAPH_Green {
            get {
                return ResourceManager.GetString("GRAPH_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Channel.
        /// </summary>
        public static string GRAPH_Green_Channel {
            get {
                return ResourceManager.GetString("GRAPH_Green_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string GRAPH_Height {
            get {
                return ResourceManager.GetString("GRAPH_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Clip Bias.
        /// </summary>
        public static string GRAPH_Height_Clip_Bias {
            get {
                return ResourceManager.GetString("GRAPH_Height_Clip_Bias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Scale.
        /// </summary>
        public static string GRAPH_Height_Scale {
            get {
                return ResourceManager.GetString("GRAPH_Height_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string GRAPH_Horizontal {
            get {
                return ResourceManager.GetString("GRAPH_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        public static string GRAPH_Hue {
            get {
                return ResourceManager.GetString("GRAPH_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string GRAPH_Image {
            get {
                return ResourceManager.GetString("GRAPH_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of Refraction.
        /// </summary>
        public static string GRAPH_Index_of_Refraction {
            get {
                return ResourceManager.GetString("GRAPH_Index_of_Refraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited.
        /// </summary>
        public static string GRAPH_Inherited {
            get {
                return ResourceManager.GetString("GRAPH_Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Type.
        /// </summary>
        public static string GRAPH_Input_Type {
            get {
                return ResourceManager.GetString("GRAPH_Input_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Parameters.
        /// </summary>
        public static string GRAPH_Instance_Parameters {
            get {
                return ResourceManager.GetString("GRAPH_Instance_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string GRAPH_Intensity {
            get {
                return ResourceManager.GetString("GRAPH_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        public static string GRAPH_Iterations {
            get {
                return ResourceManager.GetString("GRAPH_Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string GRAPH_Light {
            get {
                return ResourceManager.GetString("GRAPH_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightness.
        /// </summary>
        public static string GRAPH_Lightness {
            get {
                return ResourceManager.GetString("GRAPH_Lightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosity.
        /// </summary>
        public static string GRAPH_Luminosity {
            get {
                return ResourceManager.GetString("GRAPH_Luminosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosity Randomness.
        /// </summary>
        public static string GRAPH_Luminosity_Randomness {
            get {
                return ResourceManager.GetString("GRAPH_Luminosity_Randomness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string GRAPH_Max {
            get {
                return ResourceManager.GetString("GRAPH_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Distance.
        /// </summary>
        public static string GRAPH_Max_Distance {
            get {
                return ResourceManager.GetString("GRAPH_Max_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string GRAPH_Min {
            get {
                return ResourceManager.GetString("GRAPH_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string GRAPH_Mode {
            get {
                return ResourceManager.GetString("GRAPH_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GRAPH_Name {
            get {
                return ResourceManager.GetString("GRAPH_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near.
        /// </summary>
        public static string GRAPH_Near {
            get {
                return ResourceManager.GetString("GRAPH_Near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Reduction.
        /// </summary>
        public static string GRAPH_Noise_Reduction {
            get {
                return ResourceManager.GetString("GRAPH_Noise_Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string GRAPH_Offset {
            get {
                return ResourceManager.GetString("GRAPH_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Type.
        /// </summary>
        public static string GRAPH_Out_Type {
            get {
                return ResourceManager.GetString("GRAPH_Out_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string GRAPH_Outline {
            get {
                return ResourceManager.GetString("GRAPH_Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string GRAPH_Parameters {
            get {
                return ResourceManager.GetString("GRAPH_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Pivot.
        /// </summary>
        public static string GRAPH_Pattern_Pivot {
            get {
                return ResourceManager.GetString("GRAPH_Pattern_Pivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string GRAPH_Pin {
            get {
                return ResourceManager.GetString("GRAPH_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string GRAPH_Position {
            get {
                return ResourceManager.GetString("GRAPH_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string GRAPH_Power {
            get {
                return ResourceManager.GetString("GRAPH_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoted Functions.
        /// </summary>
        public static string GRAPH_Promoted_Functions {
            get {
                return ResourceManager.GetString("GRAPH_Promoted_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoted Parameters.
        /// </summary>
        public static string GRAPH_Promoted_Parameters {
            get {
                return ResourceManager.GetString("GRAPH_Promoted_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string GRAPH_Radius {
            get {
                return ResourceManager.GetString("GRAPH_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Seed.
        /// </summary>
        public static string GRAPH_Random_Seed {
            get {
                return ResourceManager.GetString("GRAPH_Random_Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rays.
        /// </summary>
        public static string GRAPH_Rays {
            get {
                return ResourceManager.GetString("GRAPH_Rays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string GRAPH_Red {
            get {
                return ResourceManager.GetString("GRAPH_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Channel.
        /// </summary>
        public static string GRAPH_Red_Channel {
            get {
                return ResourceManager.GetString("GRAPH_Red_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string GRAPH_Resource {
            get {
                return ResourceManager.GetString("GRAPH_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string GRAPH_Rotation {
            get {
                return ResourceManager.GetString("GRAPH_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string GRAPH_Saturation {
            get {
                return ResourceManager.GetString("GRAPH_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string GRAPH_Scale {
            get {
                return ResourceManager.GetString("GRAPH_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string GRAPH_Section {
            get {
                return ResourceManager.GetString("GRAPH_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string GRAPH_Selected {
            get {
                return ResourceManager.GetString("GRAPH_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Only.
        /// </summary>
        public static string GRAPH_Source_Only {
            get {
                return ResourceManager.GetString("GRAPH_Source_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        public static string GRAPH_Spacing {
            get {
                return ResourceManager.GetString("GRAPH_Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string GRAPH_Style {
            get {
                return ResourceManager.GetString("GRAPH_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsurface Scattering.
        /// </summary>
        public static string GRAPH_Subsurface_Scattering {
            get {
                return ResourceManager.GetString("GRAPH_Subsurface_Scattering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string GRAPH_Text {
            get {
                return ResourceManager.GetString("GRAPH_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Format.
        /// </summary>
        public static string GRAPH_Texture_Format {
            get {
                return ResourceManager.GetString("GRAPH_Texture_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile X.
        /// </summary>
        public static string GRAPH_Tile_X {
            get {
                return ResourceManager.GetString("GRAPH_Tile_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Y.
        /// </summary>
        public static string GRAPH_Tile_Y {
            get {
                return ResourceManager.GetString("GRAPH_Tile_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        public static string GRAPH_Transform {
            get {
                return ResourceManager.GetString("GRAPH_Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string GRAPH_Translation {
            get {
                return ResourceManager.GetString("GRAPH_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string GRAPH_Type {
            get {
                return ResourceManager.GetString("GRAPH_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Displacement.
        /// </summary>
        public static string GRAPH_Use_Displacement {
            get {
                return ResourceManager.GetString("GRAPH_Use_Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string GRAPH_Value {
            get {
                return ResourceManager.GetString("GRAPH_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Name.
        /// </summary>
        public static string GRAPH_Variable_Name {
            get {
                return ResourceManager.GetString("GRAPH_Variable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string GRAPH_Vertical {
            get {
                return ResourceManager.GetString("GRAPH_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string GRAPH_Width {
            get {
                return ResourceManager.GetString("GRAPH_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _2D Preview.
        /// </summary>
        public static string MENU_2D_PREVIEW {
            get {
                return ResourceManager.GetString("MENU_2D_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _3D Preview.
        /// </summary>
        public static string MENU_3D_PREVIEW {
            get {
                return ResourceManager.GetString("MENU_3D_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string MENU_CAMERA {
            get {
                return ResourceManager.GetString("MENU_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close All Graphs.
        /// </summary>
        public static string MENU_CLOSE_ALL {
            get {
                return ResourceManager.GetString("MENU_CLOSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MENU_EDIT {
            get {
                return ResourceManager.GetString("MENU_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export Outputs.
        /// </summary>
        public static string MENU_EXPORT_OUTPUTS {
            get {
                return ResourceManager.GetString("MENU_EXPORT_OUTPUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MENU_FILE {
            get {
                return ResourceManager.GetString("MENU_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Graph Settings.
        /// </summary>
        public static string MENU_GRAPH_SETTINGS {
            get {
                return ResourceManager.GetString("MENU_GRAPH_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string MENU_LIGHT {
            get {
                return ResourceManager.GetString("MENU_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Log.
        /// </summary>
        public static string MENU_LOG {
            get {
                return ResourceManager.GetString("MENU_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string MENU_MATERIAL {
            get {
                return ResourceManager.GetString("MENU_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MENU_NEW {
            get {
                return ResourceManager.GetString("MENU_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MENU_OPEN {
            get {
                return ResourceManager.GetString("MENU_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Parameters.
        /// </summary>
        public static string MENU_PARAMETERS {
            get {
                return ResourceManager.GetString("MENU_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote to Constanst.
        /// </summary>
        public static string MENU_PROMOTE_TO_CONSTANT {
            get {
                return ResourceManager.GetString("MENU_PROMOTE_TO_CONSTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote to Function.
        /// </summary>
        public static string MENU_PROMOTE_TO_FUNCTION {
            get {
                return ResourceManager.GetString("MENU_PROMOTE_TO_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recent.
        /// </summary>
        public static string MENU_RECENT {
            get {
                return ResourceManager.GetString("MENU_RECENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string MENU_REDO {
            get {
                return ResourceManager.GetString("MENU_REDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string MENU_RESET_TO_DEFAULT {
            get {
                return ResourceManager.GetString("MENU_RESET_TO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MENU_SAVE {
            get {
                return ResourceManager.GetString("MENU_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save As.
        /// </summary>
        public static string MENU_SAVE_AS {
            get {
                return ResourceManager.GetString("MENU_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string MENU_SCENE {
            get {
                return ResourceManager.GetString("MENU_SCENE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Shelf.
        /// </summary>
        public static string MENU_SHELF {
            get {
                return ResourceManager.GetString("MENU_SHELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string MENU_UNDO {
            get {
                return ResourceManager.GetString("MENU_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Windows.
        /// </summary>
        public static string MENU_WINDOWS {
            get {
                return ResourceManager.GetString("MENU_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Nodes Horizontally.
        /// </summary>
        public static string TIP_ALIGN_HORIZONTALLY {
            get {
                return ResourceManager.GetString("TIP_ALIGN_HORIZONTALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Nodes Vertically.
        /// </summary>
        public static string TIP_ALIGN_VERTICALLY {
            get {
                return ResourceManager.GetString("TIP_ALIGN_VERTICALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Size to Selected Nodes.
        /// </summary>
        public static string TIP_APPLY_SIZE {
            get {
                return ResourceManager.GetString("TIP_APPLY_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Function.
        /// </summary>
        public static string TIP_EDIT_FUNCTION {
            get {
                return ResourceManager.GetString("TIP_EDIT_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit nodes into view.
        /// </summary>
        public static string TIP_FIT_VIEW {
            get {
                return ResourceManager.GetString("TIP_FIT_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit image into view.
        /// </summary>
        public static string TIP_IMAGE_FIT_VIEW {
            get {
                return ResourceManager.GetString("TIP_IMAGE_FIT_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Custom Function.
        /// </summary>
        public static string TIP_REMOVE_CUSTOM_FUNCTION {
            get {
                return ResourceManager.GetString("TIP_REMOVE_CUSTOM_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset zoom to 100%.
        /// </summary>
        public static string TIP_RESET_ZOOM {
            get {
                return ResourceManager.GetString("TIP_RESET_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle UV view.
        /// </summary>
        public static string TIP_TOGGLE_UV {
            get {
                return ResourceManager.GetString("TIP_TOGGLE_UV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string TIP_ZOOM_IN {
            get {
                return ResourceManager.GetString("TIP_ZOOM_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string TIP_ZOOM_OUT {
            get {
                return ResourceManager.GetString("TIP_ZOOM_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D Preview.
        /// </summary>
        public static string TITLE_2D_PREVIEW {
            get {
                return ResourceManager.GetString("TITLE_2D_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Preview.
        /// </summary>
        public static string TITLE_3D_PREVIEW {
            get {
                return ResourceManager.GetString("TITLE_3D_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment....
        /// </summary>
        public static string TITLE_COMMENT {
            get {
                return ResourceManager.GetString("TITLE_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Format.
        /// </summary>
        public static string TITLE_DEFAULT_FORMAT {
            get {
                return ResourceManager.GetString("TITLE_DEFAULT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Size.
        /// </summary>
        public static string TITLE_DEFAULT_SIZE {
            get {
                return ResourceManager.GetString("TITLE_DEFAULT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Outputs.
        /// </summary>
        public static string TITLE_EXPORT_OUTPUTS {
            get {
                return ResourceManager.GetString("TITLE_EXPORT_OUTPUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been modified. Do you want to save the changes?.
        /// </summary>
        public static string TITLE_HAS_BEEN_MODIFIED {
            get {
                return ResourceManager.GetString("TITLE_HAS_BEEN_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string TITLE_LOG {
            get {
                return ResourceManager.GetString("TITLE_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string TITLE_NEW {
            get {
                return ResourceManager.GetString("TITLE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Name.
        /// </summary>
        public static string TITLE_PARAMETER_NAME {
            get {
                return ResourceManager.GetString("TITLE_PARAMETER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string TITLE_PARAMETERS {
            get {
                return ResourceManager.GetString("TITLE_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT.
        /// </summary>
        public static string TITLE_RECENT {
            get {
                return ResourceManager.GetString("TITLE_RECENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Parameter.
        /// </summary>
        public static string TITLE_REMOVE_PARAMETER {
            get {
                return ResourceManager.GetString("TITLE_REMOVE_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string TITLE_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("TITLE_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string TITLE_SEARCH {
            get {
                return ResourceManager.GetString("TITLE_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate Files.
        /// </summary>
        public static string TITLE_SEPARATE_FILES {
            get {
                return ResourceManager.GetString("TITLE_SEPARATE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf.
        /// </summary>
        public static string TITLE_SHELF {
            get {
                return ResourceManager.GetString("TITLE_SHELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string TITLE_SIZE {
            get {
                return ResourceManager.GetString("TITLE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string TITLE_TEMPLATE {
            get {
                return ResourceManager.GetString("TITLE_TEMPLATE", resourceCulture);
            }
        }
    }
}
